sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_adaptive_blend.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_adaptive_patch.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_badnet.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_blend.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_dynamic.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_SIG.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_TaCT.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_none.slurm