sbatch slurm_scripts/ct_cleanse/ct_cleanse_cifar_adaptive_blend.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_cifar_adaptive_patch.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_adaptive_blend.slurm
sbatch slurm_scripts/ct_cleanse/ct_cleanse_gtsrb_adaptive_patch.slurm