sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_adaptive_blend.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_adaptive_patch.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_badnet.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_blend.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_dynamic.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_SIG.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_TaCT.slurm
sbatch slurm_scripts/train_on_strip_cleansed/gtsrb_none.slurm