sbatch ablation/p_rate_cleanse/adaptive_blend_0.1.slurm
sbatch ablation/p_rate_cleanse/adaptive_blend_0.001.slurm
sbatch ablation/p_rate_cleanse/adaptive_patch_0.1.slurm
sbatch ablation/p_rate_cleanse/adaptive_patch_0.001.slurm
sbatch ablation/p_rate_cleanse/adaptive_blend_0.005.slurm
sbatch ablation/p_rate_cleanse/adaptive_blend_0.01.slurm
sbatch ablation/p_rate_cleanse/adaptive_blend_0.05.slurm
sbatch ablation/p_rate_cleanse/adaptive_patch_0.005.slurm
sbatch ablation/p_rate_cleanse/adaptive_patch_0.01.slurm
sbatch ablation/p_rate_cleanse/adaptive_patch_0.05.slurm