sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_adaptive_blend.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_adaptive_patch.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_badnet.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_blend.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_dynamic.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_SIG.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_TaCT.slurm
sbatch slurm_scripts/scan_cleanse/scan_cleanse_gtsrb_none.slurm